### ISSUE TITLE
Real world example

### ISSUE THREAD

**Issue by pierissimo** [AKolodeev/redux-promising-modals#13]
I quite like this approach to modals, it looks really scalable.
However, it's not really clear how to use it in a real world project.
Can you provide some examples of connected modals?

**Comment by AKolodeev** [comment]
Hi, @pierissimo. I thought about example too. I'm going to write it this week :)

**Comment by AKolodeev** [comment]
@pierissimo, I've added react example [here](https://github.com/AKolodeev/redux-promising-modals/tree/master/example) and published it at [github pages](https://akolodeev.github.io/redux-promising-modals/). Am I closing the ticket?

**Comment by pierissimo** [comment]
@AKolodeev the example is perfect.
Thanks, I'm closing
