### ISSUE TITLE
No typescript typings in npm module

### ISSUE THREAD

**Issue by vass-david** [AKolodeev/redux-promising-modals#27]
My editor just told me, that it's missing typings for `redux-promising-modals` which I've just installed. Looking into node_modules I've figured out that it's true. I believe that's not on purpose, right?

**Comment by AKolodeev** [comment]
Hi, David,
That's true. I've updated the codebase to support TypeScript but I haven't actually released a new version of the library. I don't remember what were the problems about but I think it was related to build tools...
If you have time you can investigate it (just try to run `npm run build` and see the output) and make a pull request. I'll be glad to add types :)

**Comment by vass-david** [comment]
Sure, will try.

**Comment by vass-david** [comment]
I've cloned your repo, run `npm install` (btw you have bunch of vulnerabilities according to npm audit), `npm run build` and I've `npm link`ed it to my app. Everything works as it should out of the box. The only thing that I was missing is interface/type for redux state, which is currently not being exported.

**Comment by AKolodeev** [comment]
David, thank you for checking :)
The vulnerabilities are being shown due to an old version of mocha and chai (BTH, I have [an open issue](https://github.com/AKolodeev/redux-promising-modals/issues/23) related to these packages ;) ).
I'll check what's wrong with interfaces and types on the weekend.

**Comment by vass-david** [comment]
Thanks! If you'll need any help, just text me.

**Comment by AKolodeev** [comment]
Hi, David,

I've started to work on the issue. Unfortunately, I won't finish today because I want to migrate the example to TypeScript to make sure that types exported correctly.

I think I'll release a new version on next Sunday. I hope, it's not a problem for you.

**Comment by vass-david** [comment]
Thanks for update! No problem. Your code is fairly simple, so I was able to recreate my own module very quickly with minimal features that I actually need right now. BTW do you have any channel where I can text you? I would like to discuss some of your design decisions, it's not an issue or a bug, so I don't want to create another issue here on github.

**Comment by AKolodeev** [comment]
Hi, David,

I'm sorry for the late answer. I had a lot of things to do.

I haven't got any channel, but you can create a new issue and we'll discuss it there :)

**Comment by AKolodeev** [comment]
Closed as the repository is not going to be supported anymore.
